#!/usr/bin/env node
/**
 * Generate .env files by analyzing code for environment variable usage
 */

import { readFileSync, writeFileSync, existsSync, readdirSync, lstatSync } from "fs";
import { extname, join, relative, basename } from "path";

const DEFAULT_OUTPUT = ".env";
const DEFAULT_OUTPUT_FORMAT = "env";

const LANGUAGE_PATTERNS = {
  // JavaScript/TypeScript: process.env.VAR, import.meta.env.VAR
  js: [
    /process\.env\.([A-Z_][A-Z0-9_]*)/g,
    /import\.meta\.env\.([A-Z_][A-Z0-9_]*)/g,
  ],
  // Python: os.getenv('VAR'), os.environ['VAR']
  py: [
    /os\.getenv\s*\(\s*["']([A-Z_][A-Z0-9_]*)["']\s*\)/g,
    /os\.environ\s*\[\s*["']([A-Z_][A-Z0-9_]*)["']\s*\]/g,
    /getenv\s*\(\s*["']([A-Z_][A-Z0-9_]*)["']\s*\)/g,
  ],
  // Go: os.Getenv("VAR")
  go: [
    /os\.Getenv\s*\(\s*["']([A-Z_][A-Z0-9_]*)["']\s*\)/g,
  ],
  // Ruby: ENV['VAR']
  rb: [
    /ENV\s*\[\s*["']([A-Z_][A-Z0-9_]*)["']\s*\]/g,
  ],
  // PHP: getenv('VAR'), $_ENV['VAR']
  php: [
    /getenv\s*\(\s*["']([A-Z_][A-Z0-9_]*)["']\s*\)/g,
    /\$_ENV\s*\[\s*["']([A-Z_][A-Z0-9_]*)["']\s*\]/g,
  ],
  // Java: System.getenv("VAR")
  java: [
    /System\.getenv\s*\(\s*["']([A-Z_][A-Z0-9_]*)["']\s*\)/g,
  ],
  // Kotlin
  kt: [
    /System\.getenv\s*\(\s*["']([A-Z_][A-Z0-9_]*)["']\s*\)/g,
    /getenv\s*\(\s*["']([A-Z_][A-Z0-9_]*)["']\s*\)/g,
  ],
  // Shell: ${VAR}, $VAR
  sh: [
    /\$\{([A-Z_][A-Z0-9_]*)\}/g,
    /\$([A-Z_][A-Z0-9_]*)\b/g,
  ],
  // C#
  cs: [
    /Environment\.GetEnvironmentVariable\s*\(\s*["']([A-Z_][A-Z0-9_]*)["']\s*\)/g,
  ],
  // YAML: ${VAR}
  yaml: [
    /\$\{([A-Z_][A-Z0-9_]*)\}/g,
  ],
  // Dockerfile ENV instructions
  dockerfile: [
    /ENV\s+([A-Z_][A-Z0-9_]*)=/g,
  ],
};

const SENSITIVE_PATTERNS = [
  /password/i,
  /secret/i,
  /key$/i,
  /token/i,
  /credential/i,
  /auth/i,
  /private/i,
  /sensitive/i,
];

const CATEGORY_PATTERNS = {
  database: [
    /database/i,
    /db_/i,
    /postgres/i,
    /mysql/i,
    /mongo/i,
    /redis/i,
    /sql_/i,
  ],
  api: [
    /^api_/i,
    /api[A-Z]/i,
    /endpoint/i,
    /base_url/i,
  ],
  auth: [
    /auth/i,
    /jwt/i,
    /session/i,
    /oauth/i,
    /token/i,
  ],
  aws: [
    /^aws_/i,
    /s3/i,
    /lambda/i,
    /ec2/i,
  ],
};

/**
 * Recursively get all files in a directory
 */
function getFiles(dir, files = []) {
  const entries = readdirSync(dir, { withFileTypes: true });

  for (const entry of entries) {
    const fullPath = join(dir, entry.name);
    if (entry.isDirectory()) {
      // Skip node_modules and hidden directories
      if (entry.name !== "node_modules" && !entry.name.startsWith(".")) {
        getFiles(fullPath, files);
      }
    } else {
      files.push(fullPath);
    }
  }

  return files;
}

/**
 * Get file extension for a file
 */
function getFileExtension(filename) {
  const ext = extname(filename).toLowerCase();
  return ext.replace(".", "");
}

/**
 * Detect environment variables in a file
 */
function detectVariablesInFile(filePath, content) {
  const ext = getFileExtension(filePath);
  const patterns = LANGUAGE_PATTERNS[ext] || [];

  const variables = new Map();

  for (const pattern of patterns) {
    let match;
    // Reset lastIndex for global regex
    pattern.lastIndex = 0;

    while ((match = pattern.exec(content)) !== null) {
      const varName = match[1];
      const lineNumber = content.substring(0, match.index).split("\n").length;
      const line = content.split("\n")[lineNumber - 1];

      if (!variables.has(varName)) {
        variables.set(varName, {
          name: varName,
          files: [],
          line: lineNumber,
          lineContent: line.trim(),
          isSensitive: SENSITIVE_PATTERNS.some((p) => p.test(varName)),
        });
      }

      variables.get(varName).files.push({
        path: filePath,
        line: lineNumber,
      });
    }
  }

  return variables;
}

/**
 * Categorize a variable
 */
function categorizeVariable(varName) {
  for (const [category, patterns] of Object.entries(CATEGORY_PATTERNS)) {
    if (patterns.some((p) => p.test(varName))) {
      return category;
    }
  }
  return "application";
}

/**
 * Generate .env file content
 */
function generateEnvContent(variables, options = {}) {
  const lines = [];
  lines.push("# ============================================");
  lines.push("# Environment Variables");
  lines.push("# Generated by env-generator plugin");
  lines.push("# ============================================");
  lines.push("");

  // Group variables by category
  const categorized = new Map();
  for (const [name, varData] of variables) {
    const category = categorizeVariable(name);
    if (!categorized.has(category)) {
      categorized.set(category, []);
    }
    categorized.get(category).push(varData);
  }

  // Add default category first if it exists
  const categories = ["application", "database", "api", "auth", "aws"];
  for (const cat of categories) {
    if (categorized.has(cat)) {
      categorized.delete(cat);
      categorized.set(cat, categorized.get(cat));
    }
  }

  // Output variables by category
  for (const [category, vars] of categorized) {
    lines.push(`# ============================================`);
    lines.push(`# ${category.charAt(0).toUpperCase() + category.slice(1)} Configuration`);
    lines.push(`# ============================================`);
    lines.push("");

    for (const varData of vars.sort((a, b) => a.name.localeCompare(b.name))) {
      if (varData.isSensitive) {
        lines.push(`# Security: Sensitive variable - keep secret`);
      }

      lines.push(`${varData.name}=${options.examples ? getExampleValue(varData.name) : ""}`);
      lines.push("");
    }
  }

  return lines.join("\n");
}

/**
 * Get an example value for a variable based on its name
 */
function getExampleValue(varName) {
  const lower = varName.toLowerCase();

  if (/url$/.test(lower) || /uri$/.test(lower)) {
    if (lower.includes("database") || lower.includes("db")) {
      return "postgresql://user:password@localhost:5432/dbname";
    }
    if (lower.includes("api")) {
      return "https://api.example.com";
    }
    return "https://example.com";
  }

  if (lower.includes("port") || lower.includes("timeout") || lower.includes("max") || lower.includes("min") || lower.includes("count") || lower.includes("size") || lower.includes("limit")) {
    return "3000";
  }

  if (lower.includes("env") || lower.includes("mode")) {
    return "development";
  }

  if (lower.includes("secret") || lower.includes("key") || lower.includes("password") || lower.includes("token")) {
    return `your_${lower}_here`;
  }

  if (lower.includes("enabled") || lower.includes("active") || lower.includes("debug") || lower.includes("verbose")) {
    return "true";
  }

  return `your_${varName.toLowerCase()}_here`;
}

/**
 * Main function
 */
async function main() {
  const args = process.argv.slice(2);
  let output = DEFAULT_OUTPUT;
  let examples = false;
  let requiredOnly = false;
  let format = DEFAULT_OUTPUT_FORMAT;

  // Parse arguments
  for (let i = 0; i < args.length; i++) {
    const arg = args[i];
    if (arg === "--output" || arg === "-o") {
      output = args[++i];
    } else if (arg === "--examples" || arg === "-e") {
      examples = true;
    } else if (arg === "--required-only" || arg === "-r") {
      requiredOnly = true;
    } else if (arg === "--format" || arg === "-f") {
      format = args[++i];
    }
  }

  // Get current working directory
  const cwd = process.cwd();
  console.log(`Scanning codebase for environment variables in: ${cwd}`);

  // Collect all files
  const allFiles = getFiles(cwd);

  // Filter by supported extensions
  const supportedExtensions = Object.keys(LANGUAGE_PATTERNS);
  const codeFiles = allFiles.filter((file) => {
    const ext = getFileExtension(file);
    return supportedExtensions.includes(ext);
  });

  console.log(`Found ${codeFiles.length} files to scan`);

  // Detect variables
  const allVariables = new Map();

  for (const file of codeFiles) {
    try {
      const content = readFileSync(file, "utf8");
      const variables = detectVariablesInFile(file, content);

      for (const [name, varData] of variables) {
        if (!allVariables.has(name)) {
          allVariables.set(name, varData);
        } else {
          // Merge file references
          const existing = allVariables.get(name);
          existing.files.push(...varData.files);
        }
      }
    } catch (error) {
      // Skip files that can't be read
    }
  }

  console.log(`Detected ${allVariables.size} unique environment variables`);

  // Generate output
  let outputContent;
  if (format === "yaml") {
    console.log("YAML format not yet implemented, falling back to env format");
    outputContent = generateEnvContent(allVariables, { examples });
  } else {
    outputContent = generateEnvContent(allVariables, { examples });
  }

  // Write output file
  writeFileSync(output, outputContent);
  console.log(`Generated ${output} with ${allVariables.size} variables`);
}

main().catch((error) => {
  console.error("Error generating .env file:", error.message);
  process.exit(1);
});